#!/bin/bash
PATH=$PATH:/usr/local/bin

a1=`python3 /opt/sensors/read_humidity.py | awk {' print $3'}`
echo "outside_humidity $a1" | curl -s --data-binary @- http://192.168.5.8:9091/metrics/job/temp

VV=`python3 /opt/sensors/read_pm.py | awk '{ print $4";"$5";"$6 }' | sed 's/,\|]//g'`

PM1=`echo $VV | cut -d';' -f1`
echo "outside_pm1 $PM1" | curl -s --data-binary @- http://192.168.5.8:9091/metrics/job/temp

PM25=`echo $VV | cut -d';' -f2`
echo "outside_pm25 $PM25" | curl -s --data-binary @- http://192.168.5.8:9091/metrics/job/temp

PM10=`echo $VV | cut -d';' -f3`
echo "outside_pm10 $PM10" | curl -s --data-binary @- http://192.168.5.8:9091/metrics/job/temp

pressure=`python3 /opt/sensors/read_pressure.py`
echo "outside_pressure $pressure" | curl -s --data-binary @- http://192.168.5.8:9091/metrics/job/temp
